---
# ansible/playbooks/update.yml

- name: "Update homelab"
  hosts: "all"

  vars_files:
    - "../manifest.yml"

  handlers:

    - name: "Reboot system"
      ansible.builtin.reboot:
        reboot_timeout: 1800
      become: true

  tasks:

    - name: "manage system Update"
      ansible.builtin.package:
        name: "*"
        state: "latest"
      become: true
      notify:
        - "Reboot system"
...
